defaults: &defaults
  tweet_user: 
    음악.공연:
      - 'MnetKR'
      - 'KBSMusicBank'
      - 'CJMusicLive'
      - 'Yoonmirae'
      - 'jucklee'
      - 'Yoonmirae'
      - 'MelodyMonthly'
      - 'love_yuna'
      - 'KihaChang'
      - 'dongryulkim'
      - 'JIFromAndromeda'
      - 'kolleen22'
      - 'ilsang'
      - 'le_petit_piano'
      - 'denniking'
    연예.오락:
      - 'BoAkwon'
      - 'psy_oppa'
      - 'special1004'
      - 'LUCKYHONGCHUL'
      - 'frog799'
      - 'lily199iu'
      - 'IBGDRGN'
      - 'followjyp'
      - 'missA_suzy'
      - 'flyx2NAL'
      - 'ShinsFriends'
      - 'teoinmbc'
      - 'Quanninomarley'
      - 'gagjidol'
      - 'follow2AM'
      - 'gyuri88'
      - 'keumkangkyung'
      - '0101xiahtic'
      - 'BeeeestDJ'
      - 'siwon407'
      - 'shfly3424'
    영화.드라마:
      - 'ssinz'
      - 'CJ_CGV'
      - 'gangjjang'
      - 'starlyshop'
      - 'moviejhp'
      - 'seeksik'
      - 'ActorLeeMinHo'
      - '1003Grace'
      - 'chocolatecat9'
      - 'Yoana81'
      - 'AsiaPrince_JKS'
      - 'seoulartcinema'
      - 'umjeewon'
      - 'imagolog'
      - 'JGshock'
    방송.언론:
      - 'SBS8news'
      - 'YTN24'
      - 'kbsnewstweet'
      - 'hanitweet'
      - 'SBSNOW'
      - 'yonhaptweet'
      - 'kyunghyang'
      - 'wikitree'
      - 'larryjunlive'
      - 'BaikJiYeon'
      - 'dodoson'
      - 'joongangilbo'
      - 'mediadaum'
      - 'MyloveKBS'
      - 'dongamedia'
      - 'mbcnews'
      - 'ohyeonho'
      - 'welovehani'
      - 'SohnPD'
      - 'SBSPD'
    스포츠:
      - 'kbsnewstweet'
      - 'yeonjae0528'
      - 'Asinnandakoo'
      - 'Kiatigers'
      - 'slion10'
      - 'jidongwon10'
      - 'mbcsportsplus'
      - 'hjg87'
      - 'JUNWOO8'
      - 'doosanbears1982'
      - 'minariboy'
      - 'robotdr22'
      - 'KBO_Scores'
      - 'namhoon'
      - 'Wyverns_Story'
      - 'KwangYong'
      - 'suwonbluewings'
      - 'FCSEOUL'
      - 'dglee20'
      - 'lotte0047'
    여행:
      - 'Kor_Visitkorea'
      - 'korail1899'
      - 'KoreanAir'
      - 'Flyasiana'
      - 'hanatour'
      - 'minaminita'
    패션.쇼핑:
      - 'OnStyle_twt'
      - 'SSG_Main'
      - 'LOTTEstory'
      - 'eHyundai_tweets'
      - 'bobbibrownkr'
      - 'Burberry_Korea'
      - 'wkorea'
      - 'passionkeeper'
      - 'bumsukchoi'
      - 'yoonanhee'
      - 'HyundaiCard'
      - 'Origins_kr'
    정치.정부:
      - 'cheolsoo0919'
      - 'GH_PARK'
      - 'wonsoonpark'
      - 'moonriver365'
      - 'kimmoonsoo1'
      - 'steelroot'
      - 'bluehousekorea'
      - 'Bulloger'
      - 'HQ_Sohn'
      - 'moonsoonc'
      - 'HurNamshik'
    경영.경제:
      - 'samsung'
      - 'seri_org'
      - 'About_Hyundai'
      - 'Solarplant'
      - 'Jungwook_Hong'
      - 'kennedian3'
      - 'diegobluff'
      - 'hongsunkim'
      - 'hmpyo'
    문화.책.작가:
      - 'kangfull74'
      - 'congjee'
      - 'oisoo'
      - 'munhakdongne'
      - 'Yes24Now'
      - 'tangripark'
      - 'siennastory'
      - 'yangheecho'
      - 'minumsa_books'
      - 'kooning11'
      - 'taiot'
      - 'silverytale'
      - 'tagtag2000'
      - 'jiwooclassic'
      - 'wisdomhouse7'
      - 'kdoosik'
      - 'i00111'
      - 'bookedit'
    미술.디자인.사진:
      - 'MMCAKOREA'
      - 'zosun_hi'
      - 'artkr'
      - 'geniusoh'
      - 'YoungSeKim'
      - 'SeoulAuctionKR'
      - '3photo'
      - 'andajung'
    IT:
      - 'LGElectronics'
      - 'googlekorea'
      - 'samsungtomorrow'
      - 'zdnetkorea'
      - 'SKtelecom'
      - 'LGUplus'
      - 'olleh'
      - 'bloter_news'
      - 'tjonthemove'
      - 'mushman1970'
      - 'oojoo'
      - 'channyun'
      - 'estima7'
      - 'mickeyk'
      - 'chanjin'
      - 'hiconcep'
      - 'BobbyRyu'
      - 'kwang82'
      - 'xguru'
      - 'FotoC'
    건강.의학:
      - 'aikecho'
      - 'Dr_Cheon_Keunah'
      - 'iSEVERANCE'
      - 'mindjj'
      - 'suhcs'
      - 'obgy66'
      - 'generaldoctor'
      - 'KHNMC'
      - 'Healthlog'
      - 'AsanMedicalNews'
      - 'ssbrmh'
      - 'snuh_hpc'
  twitter_key: "2wfjnSrPWPSTdqZVlWYyJg"
  twitter_secret: "k5iqKtaLyZlnOcVJKg5VrdSTOBPYY55ta6nvRoClo"

development:
  <<: *defaults
